version: '3.8'

services:
  db:
    image: ngindrek/mssql:arm64
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Spudoverlord13"
    volumes:
      - mssql_data:/var/opt/mssql/data # Optional: Persist data across container restarts

  api:
    build: ./api
    ports:
      - "8888:9000"
    volumes:
      - ./api:/app
    environment:
      # Configure your Yii 2 database connection here, using 'db' as the hostname
      DB_SERVER: db
      DB_PORT: 1433
      DB_DATABASE: construction-management # Assuming this is your database name
      DB_USERNAME: sa
      DB_PASSWORD: Spudoverlord13
      # YII_ENV: development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  mssql_data:
  frontend_node_modules: